#cloud-config

merge_how:
  - name: list
    settings: [append]
  - name: dict
    settings: [no_replace, recurse_list]

timezone: America/Vancouver

manage_etc_hosts: true

manage_resolv_conf: true
resolv_conf:
  nameservers:
    - 9.9.9.9

disable_root: false
ssh_pwauth: false

#user: root

# Disable default user generation (this prevents the creation of the 'debian' user)
users: []

#users:
#  - name: debian
#    shell: /bin/bash
#    sudo: ALL=(ALL) NOPASSWD:ALL
#    lock_passwd: true
#    ssh_authorized_keys:
#      - ssh-rsa A...

# Automatically expand the partition and filesystem to fill the resized disk
growpart:
  mode: auto
  devices: ['/']

resize_rootfs: true

# swap drive
disk_setup:
  /dev/vdb:
    table_type: mbr
    layout: true
    overwrite: true
fs_setup:
  - device: /dev/vdb1
    filesystem: swap

packages:
  - cron
  - sudo
  - git
  - curl
  - file
  - vim
  - needrestart
  - jq
  - python3-yaml
  - htop
  - iotop
  - nethogs
  - zip
  - unzip
  - rsync
  - gpg
  - net-tools
  - iputils-ping
  - bind9-dnsutils
  - traceroute
  - bsdextrautils

runcmd:
  - |
    #!/bin/bash

    set -e
    set -u
    set -x

    (
    mkdir -p ~/git
    cd ~/git
    rm xicod.github.io -rf
    git clone https://github.com/xicod/xicod.github.io.git
    cd xicod.github.io/system
    make
    )


