#cloud-config

merge_how:
  - name: list
    settings: [append]
  - name: dict
    settings: [no_replace, recurse_list]

package_update: true
package_upgrade: false

packages:
  - "@development-tools"
  - bind-utils
  - cronie

runcmd:
  - |
    #!/bin/bash

    set -e
    set -u
    set -x

    systemctl enable --now crond
